/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Link = {
  _type: "link";
  label?: string;
  url?: string;
};

export type Step = {
  _type: "step";
  title?: string;
  company?: string;
  website?: string;
  date?: string;
};

export type Drawing = {
  _id: string;
  _type: "drawing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  medium?: string;
  ratio?: "horizontal" | "vertical" | "square";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  stack?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  navigation?: Array<
    {
      _key: string;
    } & Link
  >;
  socials?: Array<
    {
      _key: string;
    } & Link
  >;
  contactTitle?: string;
  seo?: Seo;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type DrawingReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "drawing";
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
  projects?: {
    projectsList?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
  };
  galleryTitle?: string;
  gallery?: {
    drawingList?: Array<
      {
        _key: string;
      } & DrawingReference
    >;
  };
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  parkour?: Array<
    {
      _key: string;
    } & Step
  >;
  aboutLink?: Link;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | Link
  | Step
  | Drawing
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | Settings
  | ProjectReference
  | DrawingReference
  | Home
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "home"][0]{    _id,    title,    intro,    projects {      projectsList[] -> {        ...,        title,        stack,        description,        image {          asset -> {url}        },        link      }    },    galleryTitle,    gallery {      drawingList[] -> {        ...,        title,        image,        description,        ratio      }    },    portrait,    bio,    parkour,    aboutLink,    contactTitle,  }
export type HOMEPAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  intro: string | null;
  projects: {
    projectsList: Array<{
      _id: string;
      _type: "project";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string | null;
      slug?: Slug;
      stack: string | null;
      description: string | null;
      image: {
        asset: {
          url: string | null;
        } | null;
      } | null;
      link: string | null;
    }> | null;
  } | null;
  galleryTitle: string | null;
  gallery: {
    drawingList: Array<{
      _id: string;
      _type: "drawing";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string | null;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      description: string | null;
      medium?: string;
      ratio: "horizontal" | "square" | "vertical" | null;
    }> | null;
  } | null;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: string | null;
  parkour: Array<
    {
      _key: string;
    } & Step
  > | null;
  aboutLink: Link | null;
  contactTitle: null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0]{      "footer": {        "email": email,        "socials": socials[] {          ...,          label,          url        },        "contactTitle": contactTitle      },      navigation[] {        ...,        label,        url      },      seo {        ...,      }  }
export type SETTINGS_QUERY_RESULT = {
  footer: {
    email: string | null;
    socials: Array<{
      _key: string;
      _type: "link";
      label: string | null;
      url: string | null;
    }> | null;
    contactTitle: string | null;
  };
  navigation: Array<{
    _key: string;
    _type: "link";
    label: string | null;
    url: string | null;
  }> | null;
  seo: {
    _type: "seo";
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    _id,\n    title,\n    intro,\n    projects {\n      projectsList[] -> {\n        ...,\n        title,\n        stack,\n        description,\n        image {\n          asset -> {url}\n        },\n        link\n      }\n    },\n    galleryTitle,\n    gallery {\n      drawingList[] -> {\n        ...,\n        title,\n        image,\n        description,\n        ratio\n      }\n    },\n    portrait,\n    bio,\n    parkour,\n    aboutLink,\n    contactTitle,\n  }': HOMEPAGE_QUERY_RESULT;
    '\n    *[_type == "settings"][0]{\n      "footer": {\n        "email": email,\n        "socials": socials[] {\n          ...,\n          label,\n          url\n        },\n        "contactTitle": contactTitle\n      },\n      navigation[] {\n        ...,\n        label,\n        url\n      },\n      seo {\n        ...,\n      }\n  }': SETTINGS_QUERY_RESULT;
  }
}
